# Generated by Django 3.2.13 on 2022-08-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('recruit_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
                ('compensation', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=200)),
                ('tech', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('volunteer', models.IntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.company')),
            ],
        ),
    ]
